name: nf-scil merge checks
on:
  push:
    branches:
      - main

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: true

jobs:
  checks:
    if: github.repository == 'scilus/nf-scil'
    uses: ./.github/workflows/checks.yml
    secrets: inherit
